// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtuxbhdhyjdxfycubyrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dXhiaGRoeWpkeGZ5Y3VieXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzMzNjAsImV4cCI6MjA1NzkwOTM2MH0.2RdZDp50JSrK-jj14XDkGT8b82MCoxenyzALF-F2BOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);